---
- name: check for installed hyperfine
  shell: "hyperfine --version 2>&1 | perl -nE'say $1 if /([\\d.]+)/'"
  register: installed_hyperfine
  ignore_errors: true 
  check_mode: no

- debug: 
    msg: "local hyperfine: {{ installed_hyperfine.stdout }}"

- name: install new hyperfine
  when: "installed_hyperfine.stdout != hyperfine_target_version"
  import_tasks: install.yml
  
