" VAM
set runtimepath+=~/.vim/vim-addon-manager
call vam#ActivateAddons([ 'github:ervandew/supertab'])
call vam#ActivateAddons([ 'github:altercation/vim-colors-solarized'])
call vam#ActivateAddons([ 'github:scrooloose/nerdtree'])
call vam#ActivateAddons([ 'github:mattn/zencoding-vim'])
call vam#ActivateAddons([ 'github:yanick/vim-project'])
call vam#ActivateAddons([ 'github:tpope/vim-unimpaired'])
call vam#ActivateAddons([ 'github:tpope/vim-fugitive'])
call vam#ActivateAddons([ 'github:kien/ctrlp.vim'])
call vam#ActivateAddons([ 'github:tpope/vim-surround'])
call vam#ActivateAddons([ 'github:SirVer/ultisnips'])
call vam#ActivateAddons([ 'github:vim-perl/vim-perl'])

let g:UltiSnipsEditSplit='vertical'
cmap ,snip :UltiSnipsEdit<CR>



" some ideas stolen from http://items.sjbach.com/319/configuring-vim-right
set history=1000
"
" buffer stuff
set hidden

runtime macros/matchit.vim

set title

" show line numbers
set number

" folding 
set foldcolumn=3

" scrolling and viewport
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
set scrolloff=3

set ruler

nnoremap ' `
nnoremap ` '

" general stuff

syntax on
filetype on
filetype plugin on
filetype indent on

" visual bell
set vb


set autoindent
set textwidth=78
set backspace=indent,eol,start

set tabstop=4
set expandtab
set shiftwidth=4
set shiftround

set matchpairs+=<:>

iab phdr #! /usr/bin/perl -w
iab pdbg use Data::Dumper 'Dumper';<CR>warn Dumper [];^[hi


" Searching
set ignorecase   
set smartcase         " don't ignore case if there's a uppercase
set incsearch         " show me right now!
set hlsearch

" TList
nnoremap <silent> <F8> :Tlist<CR>


" TagExplorer
let TE_Ctags_Path = 'exuberant-ctags'
nnoremap <silent> <F7> :TagExplorer<CR>

" NerdTree
nnoremap <silent> <F9> :NERDTree<CR>


" backup stuff
set backup
set writebackup
set   backupdir=~/.vim/backup,./.backup,~/.vim/backup,.,/tmp
set   directory=~/.vim/backup,.,./.backup,/tmp

function InsertTabWrapper()
   let col = col('.') - 1
   if !col || getline('.')[col - 1] !~ '\k'
       return "\<tab>"
   else
       return "\<c-p>"
   endif
endfunction

"inoremap <tab> <c-r>=InsertTabWrapper()<cr>
" cute ai toggle
map ,<TAB> :set ai!<CR>:set ai?<CR>

" comment delimiters
map ,~ i#<ESC>59a~<ESC>o<ESC>
map ,# 60i#<ESC>o<ESC>


let mapleader = "\\"


"autocmd FileType perl source ~/.vim/my/perl_map.vim
"autocmd FileType perl map ,~ i3<ESC>59a~<ESC>o<ESC>
"autocmd FileType perl map ,3 60i3<ESC>o<ESC>

" Perl stuff

let g:Perl_AuthorName      = 'Yanick Champoux'     
let g:Perl_AuthorRef       = 'YANICK'                         
let g:Perl_Email           = 'yanick@cpan.org'            
let g:Perl_Company         = ''    

let tlist_perl_settings  = 'perl;c:constants;l:labels;p:package;s:subroutines;d:POD'

" taken from http://use.perl.org/~Ovid/journal/33567
fun! TestClassRunThisMethod()
    let save_cursor=getpos('.')
    let SAVE_TEST_METHOD=$TEST_METHOD

    call search('^sub \+\zs.*:.*Test','bcW')
    let $TEST_METHOD = expand('<cword>')
    exe '!printenv | sort'

    let $TEST_METHOD=SAVE_TEST_METHOD
    call setpos('.', save_cursor)
endfun

nnoremap <expr> ,tm TestClassRunThisMethod()

" ack for grep
set grepprg=ack\ --nocolor\ --nogroup\ '$*'\ *\ /dev/null
nmap <C-v><C-n> :cnext<CR>
imap <C-v><C-n> <Esc><C-v><C-n>
nmap <C-v><C-p> :cprev<CR>
imap <C-v><C-p> <Esc><C-v><C-p>

" begone, vile HTML indentation
autocmd BufEnter *.html setlocal indentexpr= 

set complete=.,w,b,u,t " omits ',i'. This avoids full file scans.

" ================= colorscheme ==============================
" gui
set t_Co=256
let g:solarized_termcolors=256
colorscheme solarized

hi search ctermbg=223 ctermfg=238
hi incsearch ctermbg=216 ctermfg=242

function! PerlMappings()
    " run the code
    noremap <buffer> <leader>r :!perl %<cr>
 
    " or check that it compiles
    noremap <buffer> <leader>r :!perl -c %<cr>
 
    " or run tall of the tests for it
    noremap <buffer> <leader>t :call TestModuleCoverage()<cr>
endfunction
 
function! PerlTestMappings()
    noremap <buffer> <leader>r :!prove -vl %<cr>
 
    " or check that it compiles
    noremap <buffer> <leader>r :!perl -c %<cr>
 
    noremap <buffer> <leader>t :!prove -vl %<CR>
endfunction
 
function! TestModuleCoverage()
    let filename = bufname('%')
 
    let tests = system('covered covering --source_file="'. filename .'"')
 
    let result  = split( tests, "\n" )
 
    if empty(result)
        echomsg "No tests found for: ". filename
    else
        execute ':!prove  ' . join(result)
    endif
endfunction

au BufRead,BufNewFile *.t set filetype=perl | compiler perlprove

au BufRead,BufNewFile entry* set filetype=galuga

map ,rf <Esc>:'<,'>! ~/bin/extract_perl_sub.pl<CR>

" copy filepath (relative) in unnamed buffer
nmap cf :let @"=expand("%")<CR>

" perlprove
au BufRead,BufNewFile *.t set filetype=perl | compiler perlprove

" http://babyl.dyndns.org/techblog/entry/statement-toggler
vmap <leader>f :! ~/bin/postfix_toggle.pl<CR>

" package name
vmap <leader>pn ! ~/bin/path2packagename.pl %<CR>

" from http://www.slideshare.net/c9s/perlhacksonvim (Cornelius++)
nmap <C-x><C-i> :call InstallCPANModule()<CR>
function! InstallCPANModule()
    let l = getline('.')
    let cw = substitute( expand('<cWORD>'), ";$", "", "g" )
    let cw = substitute( cw, "['\"]", "", "g" )
    echo "installing module " . cw . "\n"
    exec "!cpanm " . cw
    echo "done\n"
endfunction

map <F12> :!ptags<CR>

" allow creation of directories on-the-fly
function s:MkNonExDir(file, buf)
    if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
        let dir=fnamemodify(a:file, ':h')
        if !isdirectory(dir)
            call mkdir(dir, 'p')
        endif
    endif
endfunction

augroup BWCCreateDir
    autocmd!
    autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END

map <S-F1> <ESC>:call Perl_perldoc()<CR>

