# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

## Aliases

source ~/.bash/aliases

#
# colors!
export TERM=screen-256color
export ADOBE_SVG_VIEWER_PATH=/usr/lib/adobesvg

source $HOME/.bash/mine.bash

#  Three hurrahs for Michael!
alias padoff='sudo modprobe -r psmouse'
alias padon='sudo modprobe psmouse'

alias pinstall="pinto install --message='proxy install' -v --pull"
alias ppull="pinto pull -v"

########################################
# vim
########################################
alias pvim="gvim +'Project project.vim'"

# me <3 vim
export EDITOR=vim
export SVN_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR

### Catalyst aliases, stolen from the Catalyst book from MST and Kieren Diment
alias cats='CATALYST_DEBUG=0 script/*server.pl'
alias catsd='CATALYST_DEBUG=1 script/*server.pl'
alias catsdd='CATALYST_DEBUG=0 perl -d script/*server.pl -d'
alias catsddd='CATALYST_DEBUG=1 perl -d script/*server.pl'

# my private scripts
export PATH=$PATH:~/bin

# parallelism ftw
# http://www.modernperlbooks.com/mt/2012/01/speed-up-perlbrew-with-test-parallelism.html
export TEST_JOBS=9

export DBIC_TRACE_PROFILE=console

# perldoc autocompletion
complete -C perldoc-complete -o nospace -o default perldoc
complete -C perldoc-complete -o nospace -o default pod
complete -C perldoc-complete -o nospace -o default xpod

alias pod=perldoc 

alias ls='ls --color'
alias rm='rm -i'
alias top10='ps aux | sort -nk +5 | tail'

# stolen from David Perry
alias g=gvim

# taken from http://www.modernperlbooks.com/mt/2009/10/remove-the-little-pessimizations.html
alias realias='$EDITOR ~/.bash/aliases; source ~/.bash/aliases'

# From Hanekomu 
alias json_pretty='perl -0007 -MJSON -nE"say to_json(from_json(\$_, {allow_nonref=>1}),{pretty=>1})"'

alias ghist="history | grep"

# Git
source ~/.bash/git-completion.bash
alias gitka="gitk --all &"
export PATH="$PATH:~/work/git-achievements"
alias git=git-achievements

# taken from http://use.perl.org/~domm/journal/40039
sack () {
    ack "sub $1" lib
}

################################
# ssh
#
function sshdel { perl -i -ne "print unless \$. == $1" ~/.ssh/known_hosts; }


##################################################
# Misc
#

# create the dir and move in it
function ccd { 
    mkdir -p $1 && cd $1 
}


## App::GitGot and tricks
complete -C got-complete -o nospace -o default got
complete -C got-complete -o nospace -o default hack
complete -C got-complete -o nospace -o default tweak
complete -C got-complete -o nospace -o default devinc
alias hack='got mux'
function tweak { devinc $1; hack $1; }

## KDE stuff

alias seeya="qdbus org.kde.ksmserver /KSMServer logout 0 0 0"
alias goodnight="qdbus org.kde.ksmserver /KSMServer logout 0 2 2"


for file in ~/.bash/bits/*.bash
do
    source $file
done

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi

alias gimme="sudo apt-get install"

alias wp="perlbrew list"
up () {
    local perl=$1
    if [ $perl ]; then
        perlbrew use $perl@std
    fi
    local current=$(perlbrew list | grep \* | sed -e 's/\* //')
    echo "Current perl is $current"
}
